export default {
  // '-dir-2': ['dir'],
  '-music-2': ['mp3', 'ogg', 'wav', 'flac', 'ape', 'alac'],
  '-zip-2': ['zip', '7z', 'tar', 'rar', 'tgz', 'jar'],
  '-ppt': ['ppt', 'pptx'],
  '-text': ['txt', 'text'],
  '-bt': ['bt'],
  '-image': ['png', 'jpeg', 'gif', 'svg', 'jpg', 'ico'],
  '-vedio-2': [
    'mp4',
    'rm',
    'rmvb',
    'mpeg',
    'mov',
    'mtv',
    'dat',
    'wmv',
    'avi',
    '3gp',
    'amv',
    'dmv',
    'flv'
  ],
  '-ps': ['psd'],
  '-ai': ['ai'],
  '-xd': ['xd'],
  '-lr': ['lr'],
  _word_office: ['doc', 'docx'],
  _excel_office: ['xls', 'xlsx'],
  _chm: ['chm'],
  _code: ['js', 'sh', 'py', 'php', 'ts'],
  _css: ['css', 'scss', 'less', 'styl'],
  _csv: ['csv'],
  _dmg: ['dmg'],
  _exe: ['exe'],
  _oa: ['oa'],
  _pdf: ['pdf'],
  _rtf: ['rtf'],
  _md: ['md'],
  _Vue: ['vue'],
  _html: ['html', 'htm'],
  _apk: ['apk']
}
