export default {
  // '-dir-2': ['dir'],
  '-music-2': ['mp3', 'ogg', 'wav', 'flac', 'ape', 'alac'],
  '-zip-2': ['zip', '7z', 'tar', 'rar'],
  '-ppt': ['ppt', 'pptx'],
  '-text': ['txt'],
  '-bt': ['bt'],
  '-image': ['png', 'jpeg', 'gif', 'svg', 'jpg', 'ico'],
  '-vedio-2': [
    'mp4',
    'rm',
    'rmvb',
    'mpeg',
    'mov',
    'mtv',
    'dat',
    'wmv',
    'avi',
    '3gp',
    'amv',
    'dmv',
    'flv'
  ],
  '-ps': ['psd'],
  '-ai': ['ai'],
  '-xd': ['xd'],
  '-lr': ['lr'],
  _word_office: ['doc', 'docx'],
  _excel_office: ['xls', 'xlsx'],
  _chm: ['chm'],
  _code: ['js', 'sh', 'py', 'php'],
  _css: ['css', 'scss', 'less', 'styl'],
  _csv: ['csv'],
  _dmg: ['dmg'],
  _exe: ['exe'],
  _oa: ['oa'],
  _pdf: ['pdf'],
  _rtf: ['rtf'],
  _md: ['md'],
  _Vue: ['vue']
  // _file_txt: ['txt'],
  // 'file-b-16': 'dw',
  // 'file-b-17': 'fi',
  // 'file-b-18': 'br',
  // 'file-b-19': 'link',
  // 'file-s-0': 'dir',
  // file_Installation_pa: ',_Installation_pa',
  // _file_music: [',_music'],
  // _file_open: ['open'],
  // _file_pic: [',_pic'],
  // _file_ppt_office: [',_ppt_office'],
  // _file_video: [',_video'],
  // file_zip: [',_zip']
}
